on:
  webhook:
    method: get
    config:
      active: true
      force: true
      debug: false
#      logLevel: debug
jobs:
  test-curl-action:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: 'Call API'
        uses: actionsflow/axios@v1
        id: api
        with:
          url: ${{ secrets.WETTER_TEST_URL }}
          method: 'GET'
      - run: |
          echo Status: ${{ fromJSON(steps.api.outputs.data)['lat'] }}
          echo Daten: ${{ fromJSON(steps.api.outputs.data).timezone }}
          echo Header: ${{ fromJSON(steps.api.outputs.data).current.weather.0.main }}
