on:
  webhook:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 48.137000
      lon: 11.575000
      units: metric
    timeZone: UTC+02:00
    config:
      force: true
      debug: true
      logLevel: debug
      format: |
        let unix_timestamp = item.current.dt
        var utcdate = new Date(unix_timestamp * 1000)
        var date = utcdate.toLocaleString('de-DE', { timeZone: 'Europe/Berlin', timeStyle: 'medium', hourCycle: 'h24' })
        var formattedTime = date
        if(item.current.weather[0].main == "Clear") {
          item.daily[1].weather[0].main = "sonnig" + " " + formattedTime + " " + item.current.weather[0].main
          } else {
          item.daily[1].weather[0].main = "doof" + " " + formattedTime+ " " + item.current.weather[0].main
          }
        return item;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          current_cond: ${{ on.weather.outputs.current.feels_like }}
        run: |
          echo current_cond: $current_cond
  test-axios-action:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: Webex anrufen
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.WEBEX_URL_ROOSCM }}
          method: 'POST'
          accept: 200,201,204
          content-type: application/json
          body: |
            {
              "markdown" : "PING"
            }
          timeout: 10000
