on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 48.137
      lon: 11.575
      units: metric
    timeZone: UTC+02:00
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          current_cond: ${{ on.weather.outputs.current.weather.0.main }}
        run: |
          echo current_cond: $current_cond
          
