on:
  webhook:
    method: get
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 48.137000
      lon: 11.575000
      units: metric
    timeZone: UTC+02:00
    config:
      force: true
      debug: true
      active: true
      logLevel: debug
      format: |
        let unix_timestamp = item.current.dt
        var utcdate = new Date(unix_timestamp * 1000)
        var date = utcdate.toLocaleString('de-DE', { timeZone: 'Europe/Berlin', timeStyle: 'medium', hourCycle: 'h24' })
        var formattedTime = date
        if(item.current.weather[0].main == "Clear") {
          item.daily[1].weather[0].main = "sonnig" + " " + formattedTime + " " + item.current.weather[0].main
          } else {
          item.daily[1].weather[0].main = "doof" + " " + formattedTime+ " " + item.current.weather[0].main
          }
        return item;
jobs:
  call-webhook:
    name: 'Perform WEBHOOK'
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
        with:
          url: ${{ secrets.WEBEX_URL_ROOSCM }}
          body: '{"markdown": "${{ on.weather.outputs.daily.1.weather.0.main }}"}'
