on:
  webhook:
    method: post
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.webhook.outputs.method }}
          body: ${{ toJson(on.webhook.outputs.body) }}
          headers: ${{ toJson(on.webhook.outputs.headers) }}
        run: |
          echo method: $method
          echo headers $headers
          echo body: $body
  test-axios-action:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: 'Call API'
        uses: actionsflow/axios@v1
        with:
          url: ${{ secrets.FRIENDICA_POST_URL }}
          method: 'POST'
          accept: 200,201,204
          content-type: application/x-www-form-urlencoded
#           content-type: application/json
#           data: '{"status":{"title":"Tidel","status":"Stadus","source":"A Ebb"}}'
          data: status="the status you want to post"
          timeout: 10000
          basic-auth: ${{ secrets.FRIENDICA_KEY }}
          is_debug: false
