on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 48.137000
      lon: 11.575000
      units: metric
    timeZone: UTC+02:00
    config:
      logLevel: trace
      format: |
        if(current.weather.main == "Clear"){
          current.weather.main = "sonnig"
          }
        return current;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          current_cond: ${{ on.weather.outputs.current.weather.main }}
        run: |
          echo current_cond: $current_cond
      
