on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 48.137000
      lon: 11.575000
      units: metric
    timeZone: UTC+02:00
    config:
#       logLevel: debug
#       filter:
#         "daily.0.weather.0.main":
#           $eq: Clear
      format: |
        if(item.current.weather[0].main == "Clear") {
          item.daily[1].weather[0].main = "sonnig"
          } else {
          item.daily[1].weather[0].main = "doof"
          }
        return item;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          current_cond: ${{ on.weather.outputs.daily.1.weather.0.main }}
        run: |
          echo current_cond: $current_cond
