on:
  webhook:
    method: get
    config:
      active: true
      force: true
      debug: true
      logLevel: debug
jobs:
  test-curl-action:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: 'Call API'
        uses: actionsflow/axios@v1
        id: api
        with:
          url: https://hookb.in/Oeenpmm0WKcqOdYYO3ax
          method: 'POST'
          data: '{ "name": "koanama",  "job": "nixzumdoa" }'
      - run: echo ${{ steps.api.outputs.status }}
      - run: echo ${{ steps.api.outputs.data }}
      - run: echo ${{ steps.api.outputs.headers }}
      - run: |
          echo Status: ${{ steps.api.outputs.status }}
          echo Daten: ${{ steps.api.outputs.data }}
          echo Header: ${{ steps.api.outputs.headers }}
