on:
  webhook:
    method: get
jobs:
  call-webhook:
    name: 'Perform WEBHOOK'
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
        with:
          url: ${{ secrets.WEBEX_URL_ROOSCM }}
          body: '{"markdown": "ping"}'
