on:
  webhook:
    method: get
    config:
      active: true
      force: true
      debug: false
#      logLevel: debug
jobs:
  test-curl-action:
    name: 'Perform REST API'
    runs-on: ubuntu-latest
    steps:
      - name: Get openweathermap
        uses: actionsflow/axios@v1
        id: weatherapi
        with:
          url: ${{ secrets.WETTER_TEST_URL }}
          method: 'GET'
      - name: Get current date
        id: date
        run: echo "::set-output name=wotag::$(LC_TIME=de_DE.utf8 date +'%A')"
      - name: Translate current date
        id: translate
        run: |
          if [ "${{steps.date.outputs.wotag}}" = "Wednesday" ]
          then
            echo "::set-output name=wotag::'Mittwoch'"
          else
            echo "::set-output name=wotag::'Arbeitstag'"
          fi
      - if: ${{ fromJSON(steps.weatherapi.outputs.data).daily.1.clouds }}  < 10
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBEX_URL_ROOSCM }}
          body: '{"markdown": "Heute ist ${{steps.date.outputs.wotag}}<br>Morgen wird es sonnig"}'
      - if: ${{ fromJSON(steps.weatherapi.outputs.data).daily.1.clouds }}  >= 10 && steps.date.outputs.wotag == 'Tuesday'
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBEX_URL_ROOSCM }}
          body: '{"markdown": "Heute ist ${{steps.date.outputs.wotag}}<br>Morgen wird es NICHT sonnig<br>${{ fromJSON(steps.weatherapi.outputs.data).daily.1.clouds }}"}'
      - run: |
          echo Status: ${{ fromJSON(steps.weaterapi.outputs.data)['lat'] }}
          echo Daten: ${{ fromJSON(steps.weatherapi.outputs.data).timezone }}
          echo Header: ${{ fromJSON(steps.weatherapi.outputs.data).current.weather.0.main }}
          echo Wolken: ${{ fromJSON(steps.weatherapi.outputs.data).daily.1.clouds }}
          echo Wochentrag: ${{ steps.translate.outputs.wotag }}
